name: gancars
channels:
  - pytorch
  - nvidia
dependencies:
  - python==3.9
  - pip
  - pytorch=2.1.2
  - torchvision=0.16.2
  - cudatoolkit=11.8.0
  - numpy
  - click
  - pillow
  - scipy
  - requests
  - tqdm
  - ninja
  - scikit-learn
  - scikit-image
  - regex
  - scipy
  - pip:
    - einops
    - kornia
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - opencv-python
    - gdown
    - plyfile
    - urllib3
    - git+https://github.com/facebookresearch/segment-anything.git
    - git+https://github.com/IDEA-Research/GroundingDINO.git